security:
    providers:
        in_memory:
             memory:
                users:
                    ryan:
                        password: ryanpass
                        roles: 'ROLE_USER'
                    admin:
                        password: 1
                        roles: 'ROLE_ADMIN'
        our_db_provider:
            entity:
                class: AppBundle:User
                property: username
    firewalls:
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        secured_area:
            pattern:    ^/
            form_login: ~
        main:
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider
            form_login:
                login_path: login
                check_path: login
                # csrf token options
                csrf_parameter:       _csrf_token
                csrf_token_id:        authenticate
                #valid csrf
                csrf_token_generator: security.csrf.token_manager
                #csrf_token_generator: my.csrf_token_generator.id
            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/admin, roles: ROLE_ADMIN }
            - {path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    encoders:
        AppBundle\Entity\User: bcrypt